name: Push to GitHub Pages on push to master
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Deploy the site
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.82.0
          HUGO_EXTENDED: true
          TARGET_REPO: zellij-org/zellij.dev
          TARGET_BRANCH: gh-pages
          TOKEN: ${{ secrets.DEPLOY_TOKEN }}